#!/usr/bin/env python3
"""Build/check the committed standalone audit.py artifact.

Phase 3 makes the root ``audit.py`` a generated first-class distribution
artifact. The modular sources remain the source of truth for detection
semantics; this builder inlines those stdlib-compatible modules and rewrites
the client transport surface so the standalone artifact stays curl-only.

Developer prerequisite: run this builder with Python 3.10+ (CI uses 3.11).
"""

from __future__ import annotations

import argparse
import ast
import difflib
import hashlib
import io
import sys
import tokenize
from dataclasses import dataclass, field
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
STANDALONE = REPO_ROOT / "audit.py"

HEADER_START = "# GENERATED STANDALONE ARTIFACT - DO NOT EDIT BY HAND."
HEADER_END = "# END GENERATED STANDALONE HEADER"

SOURCE_PATHS = (
    "scripts/build-standalone.py",
    "scripts/audit.py",
    "api_relay_audit/channel_classifier.py",
    "api_relay_audit/_transport.py",
    "api_relay_audit/client.py",
    "api_relay_audit/context.py",
    "api_relay_audit/error_leakage.py",
    "api_relay_audit/identity_patterns.py",
    "api_relay_audit/infra_fingerprint.py",
    "api_relay_audit/latency_variance.py",
    "api_relay_audit/refusal.py",
    "api_relay_audit/reporter.py",
    "api_relay_audit/stream_integrity.py",
    "api_relay_audit/tool_substitution.py",
    "api_relay_audit/transparent_log.py",
    "api_relay_audit/web3/injection_probes.py",
)


@dataclass(frozen=True)
class Section:
    title: str
    rel_path: str | None = None
    text: str | None = None
    drop_import_prefixes: tuple[str, ...] = field(default_factory=tuple)
    replacements: tuple[tuple[str, str], ...] = field(default_factory=tuple)
    token_renames: dict[str, str] = field(default_factory=dict)
    extra_after: str = ""


STANDALONE_DOC = '''"""
API Relay Security Audit Tool v2.3 --- Standalone Edition

Generated curl-only artifact for users who want:

  curl -sO https://raw.githubusercontent.com/toby-bridges/api-relay-audit/master/audit.py
  python audit.py --key YOUR_KEY --url https://relay.example.com/v1

The detection semantics below are generated from the modular source files
listed in scripts/build-standalone.py. Do not edit this file by hand; update
the modular source and run:

  python3 scripts/build-standalone.py

The standalone keeps the product promise: no third-party Python packages,
only the standard library plus the curl executable for HTTP transport.
"""
'''


STANDALONE_TRANSPORT_WRAPPERS = r'''
def httpx_post_json(url: str, headers: dict, body: dict, timeout: int) -> dict:
    """Standalone compatibility wrapper: use curl for the modular httpx slot."""
    return curl_post_json(url, headers, body, timeout)


def httpx_get_json_data(url: str, headers: dict, timeout: int = 15):
    """Standalone compatibility wrapper: GET JSON through curl -i."""
    cmd = [
        "curl", "-sk", *curl_loopback_no_proxy_args(url),
        "-i", url, "--max-time", str(timeout), "--config", "-"
    ]
    config = "\n".join(f'header = "{k}: {v}"' for k, v in headers.items())
    r = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        input=config,
        timeout=timeout + 10,
    )
    if r.returncode != 0:
        return 0, [], "", {}
    parsed = _parse_curl_i_output(r.stdout)
    status = parsed.get("status", 0)
    text = parsed.get("body", "")
    data = []
    if status == 200:
        try:
            data = json.loads(text).get("data", [])
        except Exception:
            data = []
    return status, data, text, parsed.get("headers", {})


def httpx_raw_request(method: str, url: str, headers: dict, body: bytes,
                      content_type: str, timeout: int) -> dict:
    """Standalone compatibility wrapper: raw request through curl -i."""
    return curl_raw_request(
        method,
        url,
        headers,
        body,
        content_type,
        timeout,
        parser=_parse_curl_i_output,
    )


class _StandaloneTransport:
    curl_loopback_no_proxy_args = staticmethod(curl_loopback_no_proxy_args)
    curl_post_json = staticmethod(curl_post_json)
    httpx_post_json = staticmethod(httpx_post_json)
    curl_get_json_data = staticmethod(curl_get_json_data)
    httpx_get_json_data = staticmethod(httpx_get_json_data)
    curl_raw_request = staticmethod(curl_raw_request)
    httpx_raw_request = staticmethod(httpx_raw_request)


_transport = _StandaloneTransport()
'''


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def source_digest() -> str:
    hasher = hashlib.sha256()
    for rel in SOURCE_PATHS:
        path = REPO_ROOT / rel
        hasher.update(rel.encode("utf-8"))
        hasher.update(b"\0")
        hasher.update(read(path).replace("\r\n", "\n").encode("utf-8"))
        hasher.update(b"\0")
    return hasher.hexdigest()


def text_digest(text: str) -> str:
    return hashlib.sha256(text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


def generated_header(source_sha: str, body_sha: str) -> str:
    return (
        f"{HEADER_START}\n"
        "# Source of truth: modular files listed in scripts/build-standalone.py.\n"
        "# Regenerate after modular audit changes with:\n"
        "#   python3 scripts/build-standalone.py\n"
        "# CI verifies this generated artifact plus key behavior regressions.\n"
        f"# source_sha256: {source_sha}\n"
        f"# standalone_body_sha256: {body_sha}\n"
        f"{HEADER_END}\n"
        "\n"
    )


def strip_generated_header(text: str) -> str:
    start = text.find(HEADER_START)
    if start == -1:
        return text
    end = text.find(HEADER_END, start)
    if end == -1:
        raise SystemExit("audit.py has generated header start but no end marker")
    end = text.find("\n", end)
    if end == -1:
        return text[:start]
    next_pos = end + 1
    if text.startswith("\n", next_pos):
        next_pos += 1
    return text[:start] + text[next_pos:]


def strip_shebang(text: str) -> str:
    if text.startswith("#!"):
        newline = text.find("\n")
        if newline == -1:
            return ""
        return text[newline + 1:]
    return text


def drop_import_blocks(text: str, prefixes: tuple[str, ...]) -> str:
    """Drop import statements whose left-stripped line starts with a prefix."""
    if not prefixes:
        return text
    lines = text.splitlines(keepends=True)
    out = []
    i = 0
    while i < len(lines):
        stripped = lines[i].lstrip()
        if any(stripped.startswith(prefix) for prefix in prefixes):
            balance = lines[i].count("(") - lines[i].count(")")
            i += 1
            while i < len(lines) and balance > 0:
                balance += lines[i].count("(") - lines[i].count(")")
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "".join(out)


def rename_tokens(text: str, renames: dict[str, str]) -> str:
    if not renames:
        return text
    tokens = []
    stream = io.StringIO(text)
    for tok in tokenize.generate_tokens(stream.readline):
        if tok.type == tokenize.NAME and tok.string in renames:
            tok = tokenize.TokenInfo(
                tok.type,
                renames[tok.string],
                tok.start,
                tok.end,
                tok.line,
            )
        tokens.append(tok)
    return tokenize.untokenize(tokens)


def drop_top_level_defs(text: str, names: set[str]) -> str:
    """Drop top-level function definitions by name, preserving other text."""
    if not names:
        return text
    tree = ast.parse(text)
    ranges = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name in names:
            ranges.append((node.lineno, node.end_lineno))
    if not ranges:
        return text

    lines = text.splitlines(keepends=True)
    remove_lines = set()
    for start, end in ranges:
        remove_lines.update(range(start, end + 1))
    return "".join(
        line for idx, line in enumerate(lines, start=1)
        if idx not in remove_lines
    )


def replace_method_block(
    text: str,
    start: str,
    end: str,
    replacement: str,
    label: str = "method block",
) -> str:
    start_idx = text.find(start)
    if start_idx == -1:
        raise SystemExit(
            "Standalone generation transform failed while replacing "
            f"{label}: could not find start sentinel {start!r}. "
            "If the modular source changed shape, update "
            "scripts/build-standalone.py's transform for that source."
        )
    end_idx = text.find(end, start_idx)
    if end_idx == -1:
        raise SystemExit(
            "Standalone generation transform failed while replacing "
            f"{label}: found start sentinel {start!r} but could not find "
            f"end sentinel {end!r}. If the modular source changed shape, "
            "update scripts/build-standalone.py's transform for that source."
        )
    return text[:start_idx] + replacement + "\n\n" + text[end_idx:]


def transform_client(text: str) -> str:
    text = strip_shebang(text)
    text = drop_import_blocks(text, (
        "import httpx",
        "from api_relay_audit import _transport",
        "from api_relay_audit.stream_integrity import StreamSignals",
        "from api_relay_audit.transparent_log import ",
    ))
    text = text.replace("        self._use_curl = False\n", "        self._use_curl = True\n")
    text = text.replace(", httpx_module=httpx", "")
    text = text.replace(",\n                httpx_module=httpx", "")
    text = replace_method_block(
        text,
        "    def _stream_via_httpx(",
        "    def _stream_via_curl(",
        '''    def _stream_via_httpx(self, url: str, headers: dict, body: dict,
                          timeout: int, signals: StreamSignals,
                          hasher=None) -> None:
        """Standalone build: modular httpx streaming is replaced by curl."""
        self._stream_via_curl(url, headers, body, timeout, signals, hasher)''',
        label="api_relay_audit/client.py APIClient._stream_via_httpx",
    )
    return text


def transform_transport(text: str) -> str:
    text = strip_shebang(text)
    text = drop_import_blocks(text, ("import httpx",))
    text = drop_top_level_defs(
        text,
        {"httpx_post_json", "httpx_get_json_data", "httpx_raw_request"},
    )
    return text.strip() + "\n\n" + STANDALONE_TRANSPORT_WRAPPERS.strip() + "\n"


def transform_audit_script(text: str) -> str:
    text = strip_shebang(text)
    text = drop_import_blocks(text, (
        "from api_relay_audit.",
        "from api_relay_audit import ",
    ))
    lines = []
    for line in text.splitlines(keepends=True):
        if line.strip() == "# Allow importing from parent directory":
            continue
        if line.strip().startswith("sys.path.insert("):
            continue
        if line.lstrip().startswith("from api_relay_audit.transparent_log import "):
            continue
        lines.append(line)
    return "".join(lines)


def transform_plain_module(text: str, section: Section) -> str:
    text = strip_shebang(text)
    text = drop_import_blocks(text, section.drop_import_prefixes)
    for old, new in section.replacements:
        text = text.replace(old, new)
    return rename_tokens(text, section.token_renames)


SECTIONS = (
    Section(
        "Transparent forensic logging",
        "api_relay_audit/transparent_log.py",
    ),
    Section(
        "Stream integrity signals and verdicts",
        "api_relay_audit/stream_integrity.py",
    ),
    Section(
        "Standalone curl transport facade",
        "api_relay_audit/_transport.py",
    ),
    Section(
        "API client",
        "api_relay_audit/client.py",
    ),
    Section(
        "Markdown reporter",
        "api_relay_audit/reporter.py",
    ),
    Section(
        "Connectivity check",
        "api_relay_audit/connectivity.py",
    ),
    Section(
        "Context length scan",
        "api_relay_audit/context.py",
    ),
    Section(
        "Tool-call substitution detector",
        "api_relay_audit/tool_substitution.py",
    ),
    Section(
        "Non-Claude identity detector",
        "api_relay_audit/identity_patterns.py",
        extra_after=(
            "# Backward-compatible names used by older standalone parity tests.\n"
            "_NON_CLAUDE_STRICT_KEYWORDS = _STRICT_ASCII_KEYWORDS\n"
            "_NON_CLAUDE_CONTEXT_STRICT_KEYWORDS = _CONTEXT_STRICT_KEYWORDS\n"
        ),
    ),
    Section(
        "Refusal and prompt-leak helpers",
        "api_relay_audit/refusal.py",
    ),
    Section(
        "Error response leakage detector",
        "api_relay_audit/error_leakage.py",
    ),
    Section(
        "Web3 prompt injection probes",
        "api_relay_audit/web3/injection_probes.py",
    ),
    Section(
        "Infrastructure fingerprinting",
        "api_relay_audit/infra_fingerprint.py",
    ),
    Section(
        "Latency variance fingerprinting",
        "api_relay_audit/latency_variance.py",
    ),
    Section(
        "Upstream channel classifier",
        "api_relay_audit/channel_classifier.py",
    ),
    Section(
        "Audit orchestration",
        "scripts/audit.py",
    ),
)


def render_section(section: Section) -> str:
    if section.text is not None:
        text = section.text.strip() + "\n"
    elif section.rel_path == "api_relay_audit/_transport.py":
        text = transform_transport(read(REPO_ROOT / section.rel_path))
    elif section.rel_path == "api_relay_audit/client.py":
        text = transform_client(read(REPO_ROOT / section.rel_path))
    elif section.rel_path == "scripts/audit.py":
        text = transform_audit_script(read(REPO_ROOT / section.rel_path))
    elif section.rel_path:
        text = transform_plain_module(read(REPO_ROOT / section.rel_path), section)
    else:  # pragma: no cover - dataclass invariant
        raise AssertionError(f"Section has neither text nor path: {section}")

    text = text.strip() + "\n"
    if section.extra_after:
        text += "\n" + section.extra_after.strip() + "\n"

    return (
        "\n\n# ============================================================\n"
        f"# {section.title}\n"
        "# ============================================================\n\n"
        f"{text}"
    )


def build_body() -> str:
    parts = [
        "#!/usr/bin/env python3\n",
        STANDALONE_DOC.strip() + "\n",
        "import argparse\n",
        "import hashlib\n",
        "import json\n",
        "import os\n",
        "import re\n",
        "import shlex\n",
        "import statistics\n",
        "import subprocess\n",
        "import sys\n",
        "import tempfile\n",
        "import time\n",
        "import uuid\n",
        "from collections import Counter\n",
        "from dataclasses import dataclass, field\n",
        "from datetime import datetime, timezone\n",
        "from pathlib import Path\n",
        "from typing import List, Optional, Tuple\n",
        "from urllib.parse import urlparse\n",
    ]
    for section in SECTIONS:
        parts.append(render_section(section))
    return "".join(parts).replace("\r\n", "\n")


def build_text() -> str:
    body = build_body()
    header = generated_header(source_digest(), text_digest(body))
    if not body.startswith("#!"):
        return header + body
    first_newline = body.find("\n")
    return body[:first_newline + 1] + header + body[first_newline + 1:]


def check() -> int:
    current = read(STANDALONE)
    expected = build_text()
    if current == expected:
        print("Standalone artifact check passed.")
        return 0

    diff = "\n".join(
        difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile="audit.py (current)",
            tofile="audit.py (expected)",
            lineterm="",
            n=3,
        )
    )
    print("Standalone artifact drift detected.", file=sys.stderr)
    print(diff, file=sys.stderr)
    print("\nRegenerate with: python3 scripts/build-standalone.py", file=sys.stderr)
    return 1


def write() -> None:
    STANDALONE.write_text(build_text(), encoding="utf-8")
    print(f"Wrote {STANDALONE.relative_to(REPO_ROOT)}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Regenerate or check the standalone audit.py artifact."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if audit.py is not the generated standalone artifact.",
    )
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    if args.check:
        return check()
    write()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
